### PR TITLE
2018 frequency word list

### PR DESCRIPTION
**Pull request by hermitdave**
Addressing #9 
Adding new word lists based on 2018 data

### CODE REVIEW

**Comment by hermitdave** [comment]
@hugolpz if you are interested in having a look at data generated so far

**Comment by hugolpz** [comment]
I am only able to review English, French, Chinese. Whose are not generated yet.
I noticed you provide an "ignore that" file, nice.

**Comment by hermitdave** [comment]
i have pushed english data set @hugolpz I do notice some noise due to input data errors. let me know what you think

**Comment by hugolpz** [comment]
Hello Dave, I encourage you to merge with main branch, with a 2018 folder, can announce it as alpha as for now and request feedbacks. You can improve your process and increment your version later on.

**Pull request merged**
